### ISSUE TITLE
Need support OLED 128X32  0.91"

### ISSUE THREAD

**Issue by hallskelet** [n3bojs4/octoprint-LCD1602#1]
LCD hd44780 (16X2) don`t have I2C. For using him of I2C need additional controller.

OLED 128X32  0.91" [https://ru.aliexpress.com/item/1pcs-0-91-inch-OLED-module-0-91-white-blue-OLED-128X32-OLED-LCD-LED-Display/32672229793.html?spm=a2g0v.10010108.1000016%2FB.1.120b3a55chCa5W&isOrigTitle=true](url)
supported I2C.

This display use 3.3V power. You don`t need use level converter for rapsberry pi.
This display is quite small and well read. It is much better suited for indicating status on a papsberry pi or printer case.

**Comment by n3bojs4** [comment]
Hello Hallskelet,

you are right, this plugin has been created for people who uses hd44780 with I2C controller.
I have actually two displays with PCF8574 (I2c contrioller)  and i wrote this plugin using RPLCD python plugin (see https://github.com/dbrgn/RPLCD ).
Feel free to add support for a hd44780 connected through gpio.
I will buy an oled dispay later, and certainly i'll publish a new plugin (with more customisation).
As i said, i have two displays with i2c and a sainsmart lcd (3 with a hd44780 without i2c) in my stock it's why i had to use them :)

**Comment by n3bojs4** [comment]
i'll create another project for oled

**Comment by hallskelet** [comment]
I still can’t do the first project of the plugin :)
 I look forward to a new project.
