### ISSUE TITLE
Installation fail 

### ISSUE THREAD

**Issue by VASAPOL** [n3bojs4/octoprint-LCD1602#12]
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-MrrSb6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-MrrSb6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-MrrSb6/pip-egg-info
cwd: /tmp/pip-req-build-MrrSb6/
Complete output (3 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-MrrSb6/setup.py'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by n3bojs4** [comment]
"Hello" : a traditional way for starting a conversation with humans.
Give more details, your log is incomplete or useless...
"Best regards"

**Comment by VASAPOL** [comment]
> "Hello" : a traditional way for starting a conversation with humans.
> Give more details, your log is incomplete or useless...
> "Best regards"

I tried to install plug and it show error :
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-MrrSb6/setup.py'"'"'; file='"'"'/tmp/pip-req-build-MrrSb6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-MrrSb6/pip-egg-info
cwd: /tmp/pip-req-build-MrrSb6/
Complete output (3 lines):
Traceback (most recent call last):
File "", line 1, in 
IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-MrrSb6/setup.py'

**Comment by n3bojs4** [comment]
do you tried manual install ?

**Comment by VASAPOL** [comment]
ERROR :
pi@octopi:~ $ cd OctoPrint-Lcd1602 && python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools
pi@octopi:~/OctoPrint-Lcd1602 $

**Comment by n3bojs4** [comment]
This module is needed to install everything....
Google your issue, you need to install setuptools for python3 I think. The LCD module has been developed long time ago when octoprint was running python 2.7
Maybe your octoprint install is not good...
