### ISSUE TITLE
Fork of this for those cheap color LCD panels?

### ISSUE THREAD

**Issue by EpicLPer** [n3bojs4/octoprint-LCD1602#3]
I know that an issue may not be the best thing for this, sadly I'm not a programmer but the same thing for those cheap Amazon/eBay color LCDs which connect to the GPIO pins of the Pi would be neat! That way you could even control the whole printer just from the Pi without connecting to the website first! :)

**Comment by n3bojs4** [comment]
Hello,

You are right this is not the best place to do that but who cares ?
Gimme a good ref for this kind of lcds (under 20$), or send me one !
I own a dagoma magis printer (no screen !), and a bunch of 16x2 lcd displays are boring on my drawers, It's why i wrote this plugin.
Cheers.

**Comment by EpicLPer** [comment]
Hi,

I have these two:

https://www.amazon.de/gp/product/B01JRUH0CY/ref=oh_aui_search_asin_title?ie=UTF8&psc=1
https://www.amazon.de/gp/product/B00OFLKPG4/ref=oh_aui_search_asin_title?ie=UTF8&psc=1

Those are definitely not the best ones out there but they'd do the job just fine when the buttons on screen are big enough :)

**Comment by n3bojs4** [comment]
Hey,

I bought one it can be useful for a lot of projects i have in mind :)
Waitin the postman now !

bye

**Comment by EpicLPer** [comment]
Awesome! If you want I could help design the UI of that screen then a bit, I'm good at making designs but not so much at programming them :)

**Comment by n3bojs4** [comment]
I received it, let me play a little before :)
