### ISSUE TITLE
recommended hardware?

### ISSUE THREAD

**Issue by tewing-riffyn** [n3bojs4/octoprint-LCD1602#4]
Is there a recommended LCD board that will work with this plugin and plug directly into the raspi pin header?  I'd rather not do any soldering.

**Comment by n3bojs4** [comment]
Any hd44780 with I2c expander ( PCF8574 )

Examples : 

https://www.amazon.com/FICBOX-Serial-Backlight-Display-Arduino/dp/B071XP6PPT/ref=sr_1_3?keywords=lcd+1602+i2c&qid=1549929785&s=gateway&sr=8-3

ebay search : 

https://www.ebay.com/sch/i.html?_from=R40&_trksid=m570.l1313&_nkw=hd44780+i2c&_sacat=0


Look the chip see photo below : 

![image](https://user-images.githubusercontent.com/5824519/52602384-bf242300-2e62-11e9-9875-8595e5f921d7.png)


enjoy :)

**Comment by n3bojs4** [comment]
Hey,

I bought one it can be useful for a lot of projects i have in mind :)
Waitin the postman now !

bye
