### ISSUE TITLE
numpy issues

### ISSUE THREAD

**Issue by sarj0** [n3bojs4/octoprint-LCD1602#5]
Whether installing from the plugin manager or cloning it manually, setting up and overall installation has been impossible as numpy has been freezing and crashing everything. Anyone have any idea how to fix this/further progress with this issue? 

Thank you in advance!!

**Comment by sarj0** [comment]
update: installed numpy separately and it finally worked! However when installing the plugin, it is still trying to install numpy and freezing on the still running. Unclear as to why it would try to install numpy if it is already installed?

**Comment by sarj0** [comment]
update: I was able to install the plugin from the plugin manager after separately installing numpy!  However, how do you further access it? I keep getting the import error "could not import OctoPrint's setuptools"

**Comment by n3bojs4** [comment]
This is not an issue regarding the plugin, open issue on Octoprint github page please.
