### ISSUE TITLE
Add showing Temperature from OctoPrint-Enclosure

### ISSUE THREAD

**Issue by kalle-1989** [n3bojs4/octoprint-LCD1602#6]
Im using the OctoPrint-Enclosure with to DS18B20 Temperature Sensors. Is it possible to display these values on the LCD ?

**Comment by n3bojs4** [comment]
Hello, this is 16x2 line display we need at least a 16x4 to do that.
Nothing is impossible we can read your sensors.
I think reading /sys/bus/w1/devices/28-xxxx/w1_slave , 28-xxxx (change this to match what serial number pops up) will do the job. maybe i must re-think the plugin to let the user writing a template for displaying what he wants :)
