### ISSUE TITLE
LCD Corruption

### ISSUE THREAD

**Issue by haggis-supper** [n3bojs4/octoprint-LCD1602#8]
Seeing character corruption on the LCD every so often. Also it would be nice to have the facility to use a 20x4 lcd as well as the 16x2.

Using octoprint on a Raspberry pi 3+, with 16x2 hanging of i2c interface.

**Comment by n3bojs4** [comment]
Hello,

Please give more info about :
• os version
• python version
• python modules ( run : source oprint/bin/activate ; pip list | egrep "smbus|RPLCD" )
• lcd hardware version

**Comment by eyteam01** [comment]
Hi i had somtimes character corruption to (after a longer time) and i had modificated the code for me to use a 20x4 lcd

**Comment by n3bojs4** [comment]
can you give me informations about your hardware.
Maybe we can reuse your code and add a dropdown menu in the web interface where you can choose to use 20x4 or 16x2.
Right now i am really busy  :'( i don't have lot of time

**Comment by eyteam01** [comment]
Hi, i had a pi3B+ after a while of inactivity the character shoes corrupt on LCD.
Ok i will try to upload the modificated code for 20x4

**Comment by eyteam01** [comment]
[octoprint-LCD1602-master.zip](https://github.com/n3bojs4/octoprint-LCD1602/files/2956580/octoprint-LCD1602-master.zip)
This is the install file with the modification for the 20x4 LCD display. It is only a quick and durty version :)
